# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-elasticache-memcached
  description: Terraform Module for ElastiCache Memcached Cluster
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-modules, memcached, elasticache, aws, hcl2
